// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hslzuyenfcltoldmktix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzbHp1eWVuZmNsdG9sZG1rdGl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExODY0MDEsImV4cCI6MjA2Njc2MjQwMX0.dQvlMDs33S6bZhCdcBOTbGz3OTnMnLW1zEtMaCs3rKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);